class OpalConsole < React::Component::Base
  WELCOME_MESSAGE = <<~TEXT
  Welcome to Opal DevTools! Type 'help' for available commands.
  Type 'CTRL-?' to insert a '?' on keyboards where 'SHIFT-?' would be required.
  TEXT

  HELP_TEXT = <<~TEXT
  Available commands:
  in_panel ruby_code - execute ruby_code in the Opal DevTools panel (for developing the extension)
  in_background javascript_code - execute javascript_code in the Opal DevTools background page (for developing the extension)
  inject_opal - inject Opal into current page, only works if the page does not have Opal.
  debug_devtools - toggle debugging mode for Opal DevTools, shows generated code and other things.
  clear_screen - clear screen

  Anything else is interpreted as ruby code and executed in the context of the web page.
  TEXT

  state.count = 1
  state.debug = false

  ref :console

  event_handler :focus do |_|
    ruby_ref(:console).current.focus
  end

  def carriage_return
    state.count(state.count + 1) do
      ruby_ref(:console).current.carriage_return
    end
  end

  def console_log(message)
    ruby_ref(:console).current.log(message)
  end

  def execute_in_panel(command)
    result = Opal::Parser.eval(command)
    console_log(result)
    carriage_return
  end

  def execute_in_background(command)
    "niy"
  end

  def execute_in_page(ruby_code)
    compiled_ruby_code = Opal::Compiler.new(ruby_code, irb: true).compile
    compiled_ruby_code = compiled_ruby_code.lines[1..-1].join("\n") # remove /* Generated by Opal 1.0.0 */
    javascript_code = <<~JAVASCRIPT
      var opal_devtools_final_result = null;
      var caught = false;

      try {
        var opal_devtools_eval_result = #{compiled_ruby_code}
      } catch (e) {
        caught = true;
        opal_devtools_final_result = '' + (e.name ? e.name : 'error')  + ': ' + (e.message ? e.message : 'undefined');
      }
      
      if (!caught) { 
        if (typeof opal_devtools_eval_result === 'undefined') { opal_devtools_final_result = 'undefined' }
        else if (opal_devtools_eval_result === null) { opal_devtools_final_result = 'null' }
        else if (typeof opal_devtools_eval_result.$inspect === 'function') {
          opal_devtools_final_result = opal_devtools_eval_result.$inspect();
        } else { opal_devtools_final_result = opal_devtools_eval_result }
      }
      opal_devtools_final_result;
    JAVASCRIPT
    console_log(javascript_code) if state.debug
    %x{
      chrome.devtools.inspectedWindow.eval(javascript_code, {}, function(result, exception_info) {
        #{console_log(`result`)}
        if (exception_info) {
          if (exception_info.isError) { #{console_log(`exception_info.description`)} }
          if (exception_info.isException) { #{console_log(`exception_info.value`)} }
        }
        #{carriage_return}
      });
    }
  end

  def inject_to_page
    "niy"
  end

  def handler(command)
    begin
      if command.start_with?('in_panel')
        execute_in_panel(command[8..-1])
      elsif command.start_with?('in_background')
        execute_in_background(command[13..-1])
      elsif command.start_with?('help')
        console_log(HELP_TEXT)
        carriage_return
      elsif command.start_with?('inject_opal')
        inject_to_page
      elsif command.start_with?('debug_devtools')
        state.debug(!state.debug) do
          console_log("debug: #{state.debug}")
          carriage_return
        end
      elsif command.start_with?('clear_screen')
        ruby_ref(:console).current.clear_screen
        carriage_return
      else
        execute_in_page(command)
      end
    rescue Exception => e
      console_log(e.message)
      carriage_return
    end
  end

  render do
    Console(ref: ref(:console), autofocus: true, handler: proc { |c| handler(c) }, prompt_label: "#{state.count} > ",
            welcome_message: WELCOME_MESSAGE, on_click: :focus)
  end
end
